[tool.poetry]
name = "logar"
version = "0.1.0"
description = "Sistema de Login"
authors = ["athanio"]
license = "gpl"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
