name: Pull request

on:
   pull_request:
     branches:
       - main:
   push:

jobs:
  install:
    name: Install Packages
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2
